### ISSUE TITLE
Add delay between temp and humidity readings in example code

### ISSUE THREAD

**Issue by gorrat** [adafruit/Adafruit_AM2315#10]
The am2315test example code currently displays nan for temperature. (tested on Arduino Uno, Feather Huzzah 8266, and esp32) According to this thread ([https://forums.adafruit.com/viewtopic.php?f=19&t=117634#p591348](https://forums.adafruit.com/viewtopic.php?f=19&t=117634#p591348)), some pieces require a delay between individual temperature and humidity readings. Adding the delay fixed the problem and got me proper temperature readings on my Uno.

Please update the am2315test example code to add a delay on line 39, between individual reads. Adding 1000 ms of delay worked on my Uno. The user in the linked thread required 2000.

**Comment by ladyada** [comment]
done
