### ISSUE TITLE
Add support for reading device information

### ISSUE THREAD

**Issue by ScholliYT** [adafruit/Adafruit_AM2315#15]
I would love to see support for reading device information with this library. 

As the [datasheet ](https://cdn-shop.adafruit.com/datasheets/AM2315.pdf) (page 17) says there're registers for **model, version and ID**.

**Comment by caternuson** [comment]
What is the use case for this? Is this something you think you could PR?

**Comment by ScholliYT** [comment]
Yeah I'm working on a PR for that. My use case might be something specific, as I got multiple sensors and want to identify them by their hardware fingerprint. 

Don't know if this features fit well into the library, as it's really simple and straith forward currently.

**Comment by ladyada** [comment]
thanks for the PR! let us know when its ready to review

**Comment by ScholliYT** [comment]
I had no time to test this yet. Maybe next weekend!

**Comment by caternuson** [comment]
Closing. Looks like this sensor does not support this, at least per available documentation. 

See discussion in #16
