### ISSUE TITLE
When the sensor cable is broken

### ISSUE THREAD

**Issue by qlalfdu** [adafruit/Adafruit_AM2315#19]
Even if the cable is disconnected under normal circumstances, the previous temperature and humidity are still displayed.
This is a serious problem

I want to output an error when the sensor doesn't respond, can you tell me where to fix it?

Thank

**Comment by caternuson** [comment]
Do you get that behavior using the example sketch from this library? I2C was not really meant to be used this way. But there are some checks in the reads that should fail.

**Comment by caternuson** [comment]
Closing due to lack of response.
