### ISSUE TITLE
Initialization of AM2315 sensor seems to block when the sensor does not receive power

### ISSUE THREAD

**Issue by FlorinAndrei** [adafruit/Adafruit_AM2315#6]
Arduino Mega 2560, AM2315 sensor, blue character OLED 16x2.

http://www.adafruit.com/products/1293
http://www.adafruit.com/products/823

I've a small separate board where the 2315 is connected, with 10k pull-up resistors to V+. From the board, 4 wires go to the Mega: V+, GND, and the 2 signal wires. The signal wires connect to pins 20 and 21 on the Mega.

If the 2315 is powered on correctly, everything is fine.

On the little connection board for the 2315, if I disconnect the V+ and GND wires from the Mega, and only the 2 signal wires remain connected to the Mega, then the Mega seems to get stuck in setup() after reset, probably stuck in the 2315 initialization sequence.

If I also disconnect the 2 signal wires that go from the 2315 board to the Mega (so the 2315 is fully disconnected from the Mega), and hit reset, the Mega initializes just fine (but of course I have no readings from the sensor).

It seems like am2315.begin() cannot handle correctly the case where only the signal wires remain connected - in that case I believe that function call never returns.

The library should have some kind of timeout for a non-responding sensor, otherwise a bad sensor or a bad cable could take down the whole microcontroller.

Code excerpts:

```
#include <Adafruit_CharacterOLED.h>
#include <Wire.h>
#include <Adafruit_AM2315.h>
#include <Time.h>

// http://arduiniana.org/libraries/pstring/
// This should cure the variety of problems formatting and printing
// floats on Arduino, without using the bug-ridden native String library.
#include <PString.h>

Adafruit_CharacterOLED lcd(OLED_V2, 6, 7, 8, 9, 10, 11, 12);
Adafruit_AM2315 am2315;

int led = 13;

void setup() 
{
  pinMode(led, OUTPUT);  
  lcd.begin(16, 2);
  am2315.begin();

  // print the fixed elements on the display
  lcd.setCursor(0, 0);
  lcd.print("m:"); //print at 2,0
  lcd.setCursor(8, 0);
  lcd.print("e:"); //print at 10,0
  lcd.setCursor(0, 1);
  lcd.print("t:    C"); //print at 2,1
  lcd.setCursor(8, 1);
  lcd.print("h:    %"); //print at 10,1
}

void loop() 
{
  // The AM2315 manual recommends to not read the sensor more often
  // than once every 2 seconds.
  sensor_time_now = millis();
  if (sensor_time_now - sensor_time_last >= 2000) {
    am2315.readTemperatureAndHumidity(tmp, hum);
    sensor_time_last = sensor_time_now;
  }

// display stuff
}
```

**Comment by ladyada** [comment]
closing out some old issues - this hang is due to the arduino Wire library...not much we can do about it, if the SCL/SDA pins do not respond as expected, Wire can hang!
