### ISSUE TITLE
Am2315 read Temp/Humidity

### ISSUE THREAD

**Issue by Giang2211** [adafruit/Adafruit_AM2315#8]
Hi everyone,

I try to read data from AM2315 that i followed below link:

Everything and harware setup are Ok ! (I can detected address of AM2315). However, I cannot red out data as attached picture
http://sopwith.ismellsmoke.net/wp-content/uploads/2014/03/PI-How-To-AM2315.pdf

SSH command line interfaces:

> > > from AM2315 import\*   //OK
> > > sensor=AM2315()         //OK
> > > sensor.temperature()   // NOT OK

![image](https://cloud.githubusercontent.com/assets/16298012/19799526/6a554b08-9d21-11e6-9767-a1bfb7b76cc8.png)

**Comment by rjgates** [comment]
#Hacked Premium account giveway on telegram: https://telegram.me/G3oPx

**Comment by ladyada** [comment]
this is a different library you're talking about.
